<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AssemblyName>AvaloniaIDE.Shell</AssemblyName>
        <RootNamespace>AvaloniaIDE.Shell</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\AvaloniaIDE.Shell.States\AvaloniaIDE.Shell.States.csproj" />
        <ProjectReference Include="..\AvaloniaIDE.Shell.Abstractions\AvaloniaIDE.Shell.Abstractions.csproj" />
    </ItemGroup>
    
    <ItemGroup>
        <Content Include="Configuration/shellsettings.json" CopyToOutputDirectory="PreserveNewest"/>
        <Content Condition="'$(Configuration)' == 'Debug'"
                 Include="Configuration/shellsettings.Development.json"
                 CopyToOutputDirectory="PreserveNewest"/>
        <Content Condition="'$(Configuration)' == 'Release'"
                 Include="Configuration/shellsettings.Production.json"
                 CopyToOutputDirectory="PreserveNewest"/>
    </ItemGroup>

</Project>
